### ISSUE TITLE
how to increase the memory usage

### ISSUE THREAD

**Issue by jackleibest** [Gurkengewuerz/cefgo#3]
hi, the application will be crash in single-process mode while the memory usage over 3.5G, and the application will be blank in not single-process mode. so how to fix it?

**Comment by Gurkengewuerz** [comment]
i've never tested single mode completly because chromium aim is for multi threaded usage. See [here](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-threads) and consider using a multithreading concept!

Keep in mind the examples are just code snippets, that i've placed there for testing.
